services:
  # Backend API Service
  - type: web
    name: event-booking-ticketing-system
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://event-booking-ticketing-system-frontend.onrender.com

  # Frontend Static Site
  - type: static
    name: event-booking-ticketing-system-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_API_URL
        value: https://event-booking-ticketing-system.onrender.com
